"""Pydantic v2 models for Bilibili favorites organizer.

All models use strict type annotations and follow Bilibili API data shapes.
"""

from typing import Literal

from pydantic import BaseModel


# ──────────────────────────────────────────────────────────────────────
# Core domain models (API shapes)
# ──────────────────────────────────────────────────────────────────────


class Folder(BaseModel):
    """A Bilibili favorites folder (收藏夹).

    Based on bili-apis/docs/fav/list.md schema.
    """

    id: int
    fid: int
    mid: int
    attr: int
    title: str
    media_count: int

    @property
    def is_default(self) -> bool:
        """Return True if this is the default (系统创建) folder.

        The default folder has attr==0 (bili-apis/docs/user/space.md).
        """
        return self.attr == 0


class FavoritedItem(BaseModel):
    """A single item inside a favorites folder.

    attr values (bili-apis/docs/fav/list.md:107-108):
        0  = normal / valid
        1  = deleted (other reason)
        9  = deleted by UP主
    """

    id: int
    type: int
    title: str
    bvid: str
    upper_name: str
    upper_mid: int
    attr: int
    fav_time: int
    # Populated during classify phase from video API (not in fav API response)
    intro: str = ""
    zone_tname: str = ""

    @property
    def is_valid(self) -> bool:
        """Return True if the item is still accessible (attr==0)."""
        return self.attr == 0


class ClassificationResult(BaseModel):
    """Result of classifying a favorited item into a target folder category."""

    item: FavoritedItem
    category: str
    target_folder_title: str
    target_folder_exists: bool = False


class Operation(BaseModel):
    """A single operation within an organize plan.

    ``target`` may be a Folder (existing folder), a str (name of a folder to
    create), or None (for deletions without a target).
    """

    action: Literal["create_folder", "move", "copy", "batch_delete", "clean", "delete_folder"]
    source: Folder | None = None
    target: Folder | str | None = None
    resources: list[FavoritedItem] = []


class OrganizePlan(BaseModel):
    """A complete plan for organizing favorites, generated by a classifier."""

    total_operations: int
    folders_to_create: list[str]
    moves: list[Operation]
    deletions: list[Operation]
    summary: str
    empty_folders: list[str] = []


class VideoInfo(BaseModel):
    """Basic video metadata from the Bilibili API (video info endpoint)."""

    bvid: str
    tid: int
    tname: str


class DuplicateGroup(BaseModel):
    """A set of duplicate items found across multiple folders."""

    item: FavoritedItem
    source_folders: list[Folder]
    target_folder: Folder


class ExecutionDetail(BaseModel):
    """A single step within an execution report."""

    step: str
    status: Literal["success", "failure"]
    count: int = 0
    message: str = ""


class ExecutionReport(BaseModel):
    """Result of executing an organize plan against the B站 API.

    Tracks attempted, succeeded, and failed operations with detailed
    per-step breakdowns for post-execution review.
    """

    total_attempted: int
    succeeded: int
    failed: int
    errors: list[str] = []
    details: list[ExecutionDetail] = []


class Credentials(BaseModel):
    """Authentication credentials for Bilibili API access.

    Stored in .auth.json (git-ignored). Populated via QR-login flow.
    """

    sessdata: str
    bili_jct: str
    buvid3: str = ""
    mid: int = 0


# ──────────────────────────────────────────────────────────────────────
# File-based state models (JSON serialization between pipeline stages)
# ──────────────────────────────────────────────────────────────────────


class InvalidItemEntry(BaseModel):
    """An invalid item with its source folder reference (for state.json)."""

    item: FavoritedItem
    folder_id: int
    folder_title: str


class StateData(BaseModel):
    """Complete state produced by the ``classify`` command.

    Serialized to ``.fav-organizer/state.json``.  Contains everything
    the ``plan`` command needs to build an OrganizePlan once LLM
    classifications have been filled in.
    """

    version: str = "1.0"
    scope_kind: str  # "all" or "folder"
    scope_value: str  # folder title (or "全部" for --all)
    folders: list[Folder]
    invalid_items: list[InvalidItemEntry]
    duplicate_groups: list[DuplicateGroup]
    item_folder_map: dict[int, int]  # item_id → folder_id
    items_to_classify: list[FavoritedItem]  # with intro/zone_tname populated
    existing_folder_titles: list[str]


class ClassificationEntry(BaseModel):
    """One LLM classification decision (agent fills this in)."""

    item_id: int
    category: str  # 2-6 Chinese characters


class ClassificationResultList(BaseModel):
    """User/agent-filled LLM classifications.

    Serialized to ``.fav-organizer/classification_result.json``.
    The ``plan`` command reads this and merges with state.json to build
    the OrganizePlan.
    """

    version: str = "1.0"
    classifications: list[ClassificationEntry]
    existing_folder_titles: list[str] = []


class BatchMeta(BaseModel):
    """Pagination tracker for auto-batching when total videos exceed 50.

    Serialized to ``.fav-organizer/batch_meta.json``.  When present,
    ``classify`` skips scanning and picks the next 50-item slice from
    the existing state.json.  ``execute`` advances the offset on success.
    """

    batch_size: int = 50
    total_videos: int
    current_offset: int = 0

    @property
    def total_batches(self) -> int:
        return max((self.total_videos + self.batch_size - 1) // self.batch_size, 1)

    @property
    def current_batch(self) -> int:
        return self.current_offset // self.batch_size + 1

    @property
    def is_last_batch(self) -> bool:
        return self.current_offset + self.batch_size >= self.total_videos


# ──────────────────────────────────────────────────────────────────────
# Plan serialization (for execute command)
# ──────────────────────────────────────────────────────────────────────


class PlanResourceRef(BaseModel):
    """Lightweight reference to a favorited item for plan serialization."""

    id: int
    type: int
    bvid: str
    title: str


class PlanMoveEntry(BaseModel):
    """A move operation in serialized form."""

    source_folder_id: int
    source_folder_title: str
    target_title: str
    resources: list[PlanResourceRef]


class PlanDeleteEntry(BaseModel):
    """A delete operation in serialized form."""

    source_folder_id: int
    source_folder_title: str
    reason: str  # "invalid" | "duplicate"
    resources: list[PlanResourceRef]


class PlanFile(BaseModel):
    """Serializable organize plan for the ``execute`` command.

    Serialized to ``.fav-organizer/plan.json``.  Uses simple types
    (no nested Folder/FavoritedItem unions) for unambiguous
    deserialization.
    """

    version: str = "1.0"
    folders_to_create: list[str]
    moves: list[PlanMoveEntry]
    deletions: list[PlanDeleteEntry]
    empty_folders: list[str] = []
    summary: str = ""
