"""Pydantic v2 models for Bilibili favorites organizer.

All models use strict type annotations and follow Bilibili API data shapes.
"""

from typing import Literal

from pydantic import BaseModel


class Folder(BaseModel):
    """A Bilibili favorites folder (收藏夹).

    Based on bili-apis/docs/fav/list.md schema.
    """

    id: int
    fid: int
    mid: int
    attr: int
    title: str
    media_count: int

    @property
    def is_default(self) -> bool:
        """Return True if this is the default (系统创建) folder.

        The default folder has attr==0 (bili-apis/docs/user/space.md).
        """
        return self.attr == 0


class FavoritedItem(BaseModel):
    """A single item inside a favorites folder.

    attr values (bili-apis/docs/fav/list.md:107-108):
        0  = normal / valid
        1  = deleted (other reason)
        9  = deleted by UP主
    """

    id: int
    type: int
    title: str
    bvid: str
    upper_name: str
    upper_mid: int
    attr: int
    fav_time: int

    @property
    def is_valid(self) -> bool:
        """Return True if the item is still accessible (attr==0)."""
        return self.attr == 0


class ClassificationResult(BaseModel):
    """Result of classifying a favorited item into a target folder category."""

    item: FavoritedItem
    category: str
    target_folder_title: str
    target_folder_exists: bool = False


class Operation(BaseModel):
    """A single operation within an organize plan.

    ``target`` may be a Folder (existing folder), a str (name of a folder to
    create), or None (for deletions without a target).
    """

    action: Literal["create_folder", "move", "copy", "batch_delete", "clean"]
    source: Folder | None = None
    target: Folder | str | None = None
    resources: list[FavoritedItem] = []


class OrganizePlan(BaseModel):
    """A complete plan for organizing favorites, generated by a classifier."""

    total_operations: int
    folders_to_create: list[str]
    moves: list[Operation]
    deletions: list[Operation]
    summary: str
    empty_folders: list[str] = []


class VideoInfo(BaseModel):
    """Basic video metadata from the Bilibili API (video info endpoint)."""

    bvid: str
    tid: int
    tname: str


class DuplicateGroup(BaseModel):
    """A set of duplicate items found across multiple folders."""

    item: FavoritedItem
    source_folders: list[Folder]
    target_folder: Folder


class ExecutionDetail(BaseModel):
    """A single step within an execution report."""

    step: str
    status: Literal["success", "failure"]
    count: int = 0
    message: str = ""


class ExecutionReport(BaseModel):
    """Result of executing an organize plan against the B站 API.

    Tracks attempted, succeeded, and failed operations with detailed
    per-step breakdowns for post-execution review.
    """

    total_attempted: int
    succeeded: int
    failed: int
    errors: list[str] = []
    details: list[ExecutionDetail] = []


class Credentials(BaseModel):
    """Authentication credentials for Bilibili API access.

    Stored in .auth.json (git-ignored). Populated via QR-login flow.
    """

    sessdata: str
    bili_jct: str
    buvid3: str = ""
    mid: int = 0
